<?php

/**
 * This is the model base class for the table "comment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comment".
 *
 * Columns in table "comment" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $comment
 * @property string $dates
 * @property string $num_auto
 *
 */
abstract class BaseComment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'glonass.comment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comment|Comments', $n);
	}

	public static function representingColumn() {
		return 'comment';
	}

	public function rules() {
		return array(
			array('comment, dates, num_auto', 'required'),
			array('num_auto', 'length', 'max'=>20),
			array('id, comment, dates, num_auto', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'comment' => Yii::t('app', 'Comment'),
			'dates' => Yii::t('app', 'Dates'),
			'num_auto' => Yii::t('app', 'Num Auto'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('dates', $this->dates, true);
		$criteria->compare('num_auto', $this->num_auto, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}