<?php

/**
 * This is the model base class for the table "sims".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sims".
 *
 * Columns in table "sims" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $sim_num
 * @property string $phone_num
 *
 */
abstract class BaseSims extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'glonass_crm.sims';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Sims|Sims', $n);
	}

	public static function representingColumn() {
		return 'sim_num';
	}

	public function rules() {
		return array(
			array('sim_num, phone_num', 'required'),
			array('sim_num', 'length', 'max'=>30),
			array('phone_num', 'length', 'max'=>11),
			array('id, sim_num, phone_num', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'sim_num' => Yii::t('app', 'Sim Num'),
			'phone_num' => Yii::t('app', 'Phone Num'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('sim_num', $this->sim_num, true);
		$criteria->compare('phone_num', $this->phone_num, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}