<?php

/**
 * This is the model base class for the table "trucks".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Trucks".
 *
 * Columns in table "trucks" available as properties of the model,
 * followed by relations of table "trucks" available as properties of the model.
 *
 * @property integer $id
 * @property string $plate
 * @property double $daily_license_fee
 * @property string $fio
 * @property integer $is_act
 * @property integer $is_conctract
 * @property string $contract_number
 * @property string $act_number
 * @property double $balance_license_fee
 * @property string $comment
 * @property integer $installation_is_close
 * @property integer $type
 * @property integer $is_zernovoz
 * @property string $phone_sim
 * @property string $number_sim
 * @property integer $is_wialon
 * @property string $login_wialon
 * @property string $pass
 * @property integer $isCredit
 * @property integer $isProblem
 * @property integer $installManId
 *
 * @property Payments[] $payments
 */
abstract class BaseTrucks extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'glonass_crm.trucks';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Trucks|Trucks', $n);
	}

	public static function representingColumn() {
		return 'plate';
	}

	public function rules() {
		return array(
			array('plate, daily_license_fee', 'required'),
			array('is_act, is_conctract, installation_is_close, type, is_zernovoz, is_wialon, isCredit, isProblem, installManId', 'numerical', 'integerOnly'=>true),
			array('daily_license_fee, balance_license_fee', 'numerical'),
			array('plate, contract_number, act_number', 'length', 'max'=>25),
			array('phone_sim', 'length', 'max'=>14),
			array('number_sim', 'length', 'max'=>21),
			array('login_wialon, pass', 'length', 'max'=>11),
			array('fio, comment', 'safe'),
			array('fio, is_act, is_conctract, contract_number, act_number, balance_license_fee, comment, installation_is_close, type, is_zernovoz, phone_sim, number_sim, is_wialon, login_wialon, pass, isCredit, isProblem, installManId', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, plate, daily_license_fee, fio, is_act, is_conctract, contract_number, act_number, balance_license_fee, comment, installation_is_close, type, is_zernovoz, phone_sim, number_sim, is_wialon, login_wialon, pass, isCredit, isProblem, installManId', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'payments' => array(self::HAS_MANY, 'Payments', 'plate'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'plate' => Yii::t('app', 'Plate'),
			'daily_license_fee' => Yii::t('app', 'Daily License Fee'),
			'fio' => Yii::t('app', 'Fio'),
			'is_act' => Yii::t('app', 'Is Act'),
			'is_conctract' => Yii::t('app', 'Is Conctract'),
			'contract_number' => Yii::t('app', 'Contract Number'),
			'act_number' => Yii::t('app', 'Act Number'),
			'balance_license_fee' => Yii::t('app', 'Balance License Fee'),
			'comment' => Yii::t('app', 'Comment'),
			'installation_is_close' => Yii::t('app', 'Installation Is Close'),
			'type' => Yii::t('app', 'Type'),
			'is_zernovoz' => Yii::t('app', 'Is Zernovoz'),
			'phone_sim' => Yii::t('app', 'Phone Sim'),
			'number_sim' => Yii::t('app', 'Number Sim'),
			'is_wialon' => Yii::t('app', 'Is Wialon'),
			'login_wialon' => Yii::t('app', 'Login Wialon'),
			'pass' => Yii::t('app', 'Pass'),
			'isCredit' => Yii::t('app', 'Is Credit'),
			'isProblem' => Yii::t('app', 'Is Problem'),
			'installManId' => Yii::t('app', 'Install Man'),
			'payments' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('plate', $this->plate, true);
		$criteria->compare('daily_license_fee', $this->daily_license_fee);
		$criteria->compare('fio', $this->fio, true);
		$criteria->compare('is_act', $this->is_act);
		$criteria->compare('is_conctract', $this->is_conctract);
		$criteria->compare('contract_number', $this->contract_number, true);
		$criteria->compare('act_number', $this->act_number, true);
		$criteria->compare('balance_license_fee', $this->balance_license_fee);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('installation_is_close', $this->installation_is_close);
		$criteria->compare('type', $this->type);
		$criteria->compare('is_zernovoz', $this->is_zernovoz);
		$criteria->compare('phone_sim', $this->phone_sim, true);
		$criteria->compare('number_sim', $this->number_sim, true);
		$criteria->compare('is_wialon', $this->is_wialon);
		$criteria->compare('login_wialon', $this->login_wialon, true);
		$criteria->compare('pass', $this->pass, true);
		$criteria->compare('isCredit', $this->isCredit);
		$criteria->compare('isProblem', $this->isProblem);
		$criteria->compare('installManId', $this->installManId);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}