<?php

/**
 * This is the model base class for the table "tarifs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tarifs".
 *
 * Columns in table "tarifs" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $amount
 * @property string $name
 * @property integer $type
 *
 */
abstract class BaseTarifs extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'glonass_crm.tarifs';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tarifs|Tarifs', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('amount, name, type', 'required'),
			array('amount, type', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('id, amount, name, type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'amount' => Yii::t('app', 'Amount'),
			'name' => Yii::t('app', 'Name'),
			'type' => Yii::t('app', 'Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('amount', $this->amount);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('type', $this->type);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}