<?php

/**
 * This is the model base class for the table "sanctions".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sanctions".
 *
 * Columns in table "sanctions" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $obj_id
 * @property string $date_create
 * @property string $date_out
 * @property integer $status
 * @property string $comment
 * @property integer $glonass
 * @property integer $user_id_add
 * @property integer $user_id_remove
 * @property integer $glonass_id
 * @property integer $provider_id
 *
 */
abstract class BaseSanctions extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sanctions';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Sanctions|Sanctions', $n);
	}

	public static function representingColumn() {
		return 'date_create';
	}

	public function rules() {
		return array(
			array('obj_id, status, glonass, user_id_add, user_id_remove, glonass_id, provider_id', 'numerical', 'integerOnly'=>true),
			array('date_create, date_out, comment', 'safe'),
			array('obj_id, date_create, date_out, status, comment, glonass, user_id_add, user_id_remove, glonass_id, provider_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, obj_id, date_create, date_out, status, comment, glonass, user_id_add, user_id_remove, glonass_id, provider_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'obj_id' => Yii::t('app', 'Obj'),
			'date_create' => Yii::t('app', 'Date Create'),
			'date_out' => Yii::t('app', 'Date Out'),
			'status' => Yii::t('app', 'Status'),
			'comment' => Yii::t('app', 'Comment'),
			'glonass' => Yii::t('app', 'Glonass'),
			'user_id_add' => Yii::t('app', 'User Id Add'),
			'user_id_remove' => Yii::t('app', 'User Id Remove'),
			'glonass_id' => Yii::t('app', 'Glonass'),
			'provider_id' => Yii::t('app', 'Provider'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('obj_id', $this->obj_id);
		$criteria->compare('date_create', $this->date_create, true);
		$criteria->compare('date_out', $this->date_out, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('comment', $this->comment, true);
		$criteria->compare('glonass', $this->glonass);
		$criteria->compare('user_id_add', $this->user_id_add);
		$criteria->compare('user_id_remove', $this->user_id_remove);
		$criteria->compare('glonass_id', $this->glonass_id);
		$criteria->compare('provider_id', $this->provider_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}