<?php

/**
 * This is the model base class for the table "autos_archive".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AutosArchive".
 *
 * Columns in table "autos_archive" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $num_auto
 * @property integer $prov
 * @property integer $trader
 * @property string $windows
 * @property string $window_from
 * @property string $window_to
 * @property integer $confirm
 * @property string $date_cre
 * @property integer $culture
 * @property integer $receiver
 * @property string $phone
 * @property integer $deleted
 * @property string $arrived
 * @property string $delete_date
 * @property string $delete_who
 * @property integer $is_dirty
 *
 */
abstract class BaseAutosArchive extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cms.autos_archive';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AutosArchive|AutosArchives', $n);
	}

	public static function representingColumn() {
		return 'num_auto';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id, prov, trader, confirm, culture, receiver, deleted, is_dirty', 'numerical', 'integerOnly'=>true),
			array('num_auto', 'length', 'max'=>25),
			array('arrived', 'length', 'max'=>1),
			array('delete_who', 'length', 'max'=>50),
			array('windows, window_from, window_to, date_cre, phone, delete_date', 'safe'),
			array('num_auto, prov, trader, windows, window_from, window_to, confirm, date_cre, culture, receiver, phone, deleted, arrived, delete_date, delete_who, is_dirty', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, num_auto, prov, trader, windows, window_from, window_to, confirm, date_cre, culture, receiver, phone, deleted, arrived, delete_date, delete_who, is_dirty', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'num_auto' => Yii::t('app', 'Num Auto'),
			'prov' => Yii::t('app', 'Prov'),
			'trader' => Yii::t('app', 'Trader'),
			'windows' => Yii::t('app', 'Windows'),
			'window_from' => Yii::t('app', 'Window From'),
			'window_to' => Yii::t('app', 'Window To'),
			'confirm' => Yii::t('app', 'Confirm'),
			'date_cre' => Yii::t('app', 'Date Cre'),
			'culture' => Yii::t('app', 'Culture'),
			'receiver' => Yii::t('app', 'Receiver'),
			'phone' => Yii::t('app', 'Phone'),
			'deleted' => Yii::t('app', 'Deleted'),
			'arrived' => Yii::t('app', 'Arrived'),
			'delete_date' => Yii::t('app', 'Delete Date'),
			'delete_who' => Yii::t('app', 'Delete Who'),
			'is_dirty' => Yii::t('app', 'Is Dirty'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('num_auto', $this->num_auto, true);
		$criteria->compare('prov', $this->prov);
		$criteria->compare('trader', $this->trader);
		$criteria->compare('windows', $this->windows, true);
		$criteria->compare('window_from', $this->window_from, true);
		$criteria->compare('window_to', $this->window_to, true);
		$criteria->compare('confirm', $this->confirm);
		$criteria->compare('date_cre', $this->date_cre, true);
		$criteria->compare('culture', $this->culture);
		$criteria->compare('receiver', $this->receiver);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('deleted', $this->deleted);
		$criteria->compare('arrived', $this->arrived, true);
		$criteria->compare('delete_date', $this->delete_date, true);
		$criteria->compare('delete_who', $this->delete_who, true);
		$criteria->compare('is_dirty', $this->is_dirty);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}